# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efeaa2612154caebad344777e14ec0d2a71a0a2246e53ec6aae624ccad20b029cfeed9ca4fb179ffc507116cb1a64c1e3e1ca753a8d89052838f3399a5ac3e8d

test:
  secret_key_base: bb59d0294af07b708e834149d4d426db86c327db89624b25e08b38bf21874f0186d3dc8f7107cde5501d47b2649868e14453a9ce7a2238e04696be1b7dc5a724

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%=AppSettings.secrets.production%>
